### ISSUE TITLE
Installation from LuaRocks main fails

### ISSUE THREAD

**Issue by nopdotcom** [lua-stdlib/functional#1]
```sh 
$ sudo luarocks install std.functional

Error: No results matching query were found.
```

**Comment by gvvaughan** [comment]
Hi Jay,

Thanks for your interest in std.functional, and for the issue.  `std.functional` is not in good enough shape for a release to luarocks yet, so I haven't uploaded it.

Conversely, it does not offer anything more than the `std.functional` module in released lua-stdlib, which you can get from LuaRocks with:

    luarocks install stdlib

And access from your code with:

    local functional = require 'std.functional'

At some point, I'll finish the work for breaking stdlib apart into several modules and make announcements on the lua mailing list - in the mean time, you are most welcome to try out what I have so far, report problems and send pull-requests.

Cheers,
Gary

**Comment by nopdotcom** [comment]
That makes sense. The place that this showed up was building Zile/ZZ/Zemacs and at this point I think it's the crappy Ubuntu 16.04 5.1-only luarocks hurting me. Thanks for the information and help.
