### ISSUE TITLE
Not available on luarocks

### ISSUE THREAD

**Issue by rrthomas** [lua-stdlib/functional#5]
```
$ luarocks install --check-lua-versions std.functional
std.functional not found for Lua 5.4.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.3...

Error: No results matching query were found for Lua 5.4.
std.functional is not available for any Lua versions.
```

I searched, and it doesn't seem to be a typo in the name; I just can't find it on LuaRocks.

**Comment by taylan97** [comment]
Yes this is quite the bummer.

**Comment by gvvaughan** [comment]
Well I have no idea where that went :-/  Looks like I abandoned the working copy before pulling the trigger.

Now tagged and uploaded here:  https://luarocks.org/modules/gvvaughan/std.functional
